name: Deploy to production

on:
   workflow_dispatch:
   push:
      branches:
         - master

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      env:
         ENVIRONMENT: prod
      steps:
         - name: Checkout
           uses: actions/checkout@v4
           with:
              fetch-depth: 1

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v3
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Build image
           run: |
              SHORT_SHA=$(git rev-parse --short=7 HEAD)
              docker build -t ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]'):${SHORT_SHA} .

         - name: Push image
           run: |
              SHORT_SHA=$(git rev-parse --short=7 HEAD)
              docker push ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]'):${SHORT_SHA}

         - name: Build template deployment
           run: |
              SHORT_SHA=$(git rev-parse --short=7 HEAD)
              .deploy/build_deployment.sh STACK="${{ github.event.repository.name }}" \
              DEPLOYMENT_ENVIROMENT="${{ env.ENVIRONMENT }}" \
              IMAGE="ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]'):$SHORT_SHA" \
              CADDY_HOST="${{ vars.HOST_DNS }}" \
              CADDY_TLS="${{ vars.TLS}}" \
              > /tmp/${{ github.event.repository.name }}.${{ env.ENVIRONMENT }}.deployment.yml
           # add more environment variables here same debug.sh and deployment.template.yml before > redirect /tmp/...

         - name: Set up SSH key
           uses: webfactory/ssh-agent@v0.5.3
           with:
              ssh-private-key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

         - name: Copy deployment file to server
           run: scp -o StrictHostKeyChecking=no -P ${{ secrets.HOST_SSH_PORT}} /tmp/${{ github.event.repository.name }}.${{ env.ENVIRONMENT }}.deployment.yml deploy@${{ secrets.HOST_SSH_NAME }}:/tmp/${{ github.event.repository.name }}.${{ env.ENVIRONMENT }}.deployment.yml

         - name: Docker login on server
           run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOST_SSH_PORT }} deploy@${{ secrets.HOST_SSH_NAME }} "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}"

         - name: Pull image on server
           run: |
              SHORT_SHA=$(git rev-parse --short=7 HEAD)
              ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOST_SSH_PORT }} deploy@${{ secrets.HOST_SSH_NAME }} "docker pull ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]'):${SHORT_SHA}"

         - name: Deploy to Docker swarm
           run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOST_SSH_PORT }} deploy@${{ secrets.HOST_SSH_NAME }} "docker stack deploy -c /tmp/${{ github.event.repository.name }}.${{ env.ENVIRONMENT }}.deployment.yml ${{ github.event.repository.name }}-${{ env.ENVIRONMENT }}"

         # - name: Clean up deployment file on server
         #   if: always()
         #   run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.HOST_SSH_PORT }} deploy@${{ secrets.HOST_SSH_NAME }} "rm -f /tmp/${{ github.event.repository.name }}.${{ env.ENVIRONMENT }}.deployment.yml"

         - name: Delete deployment file locally
           if: always()
           run: rm -f /tmp/${{ github.event.repository.name }}.${{ env.ENVIRONMENT }}.deployment.yml
